# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01e6e28dab917b6ea1918666680b083c0e94a6a948e37610bd4e7c0cc594448e30ca8e89a403cdb0b9263b36e6609632a9bedaae2b661dcbd58f9f2cce8f0828

test:
  secret_key_base: 356f998dcfb187bddc581550a2f640198e09268c2824252359155cb16c25ab99370fe43de0237a7aff9b2309d3fe5553f78e8b0b8fa549157ca98e9c048f40d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
